name: Hola mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run : echo "Hola mundo"
      - name: total
        run : touch hola.txt
      - name: set text
        run : echo "hola mundo2" >> hola.txt
      - name: read file
        run : cat hola.txt      
  
  other:
    runs-on: ubuntu-latest

    steps:
      - name: ls
        run : echo "new ls"
